### PR TITLE
Typo in image path for loading page.

### PR DESCRIPTION
**Pull request by briehl**

### CODE REVIEW

**Comment by briehl** [comment]
A one-character PR seems almost silly. But it's a really important character!

**Comment by eapearson** [comment]
Actually, that was silly of me to accept without comment. There should be a duplicate of doodle in client/images for use in the loading  page so that we don't make dependencies upon plugins. Also, I've been putting individual html pages into client/pages, just to keep the root clutter down.

**Comment by briehl** [comment]
That's a good idea. I was just doing the emergency minor fix to get this working.
Would it be better to have that whole page be a small plugin? That might fit the scheme better.

**Comment by eapearson** [comment]
Actually, yes it would be. Couldn't that live in narrativemanager?

**Comment by briehl** [comment]
Probably. I'll tinker with it.

**Comment by briehl** [comment]
This'll probably necessitate a change to the narrative's nginx / container management code. That was probably the only reason we left that bit of sloppiness.

**Pull request merged**
