### PR TITLE
homology service UI prototype

### PR DESCRIPTION
**Pull request by hyoo**

### CODE REVIEW

**Comment by scanon** [comment]
Harry and Bill: Would it make sense to put this in a plugin module?

**Comment by hyoo** [comment]
Is there any document that describes what is plugin (and what should fall into plugin category)? I just started from the datasearch, since it looks very similar to what we're trying to do, but I am open to discuss. Would you please explain the big picture? I mean, in your perfect world, how it should be organized.

**Comment by scanon** [comment]
Erik and Bill can best answer this.  There is some documentation in the docs directory.  But I don't know if it is complete enough to answer your questions.  You can look at some of the examples in Erik's repos.

https://github.com/eapearson?tab=repositories

For example,

https://github.com/eapearson/kbase-ui-plugin-sample

**Comment by briehl** [comment]
For now, adding it alongside search is fine, since those complement each other. We'll have to have a discussion on how to keep things separate from the rest of the plugin setup, or migrate both data search and sequence search into plugins. That'll be non-trivial, to say the least.

In my perfect world, everything would be a plugin, and plugins would be able to pop into place in the Narrative as well and all behave nicely together. We're trying to build a bridge to that world, but it'll be a heavy task. 

Here's a flow of the steps as I see them. This is probably too much to absorb at once, but welcome to KBase. :smile:  
  1. Get kbase-ui deployed on CI, to replace ui-common. Branches of ui-common will remain in place to plug widgets into the Narrative, but the main page (dashboard, search, etc.) hasn't been updated in quite some time, so this shouldn't be terribly destructive. Still, as @scanon would way, it'll be like pulling off a band-aid - I expect a few sharp screams.
  2. Migrate the widget code in those ui-common branches into kbase-ui plugins. (as a technical detail, expose the RequireJS config for those plugins so the Narrative can just fetch them off the server). This will have two advantages: plugins can be developed separately without needing to muck about with the monolithic ui-common or narrative repos, and they can then be deployed quickly and easily.
  3. Modify the Narrative flow to use plugins directly. I'm still not sure how to architect this, or how it should work. But it will help things immensely - along with the reasons above, widgets built with SDK modules (which will be deployed elsewhere) will need to use something like this. I'd like all of the UI components in KBase to use the same apparatus.
  4. Work with the SDK team to get them working with UI elements in KBase. The ultimate final goal of this whole exercise is to enable third party (and first party, frankly) devs to make KBase methods, data objects, and viewers using the same tools and mechanisms that we use. My perfect world is one where someone can come in with a new method, and make a new widget that easily extends viewers that we have, without having to duplicate code all over the place and deploy different things all over.

Also tagging @eapearson @thomasoniii and @nconrad here. I'm pretty sure they know the scope of things, but it's closing up on the time to have some kind of planning conversation.

**Comment by mlhenderson** [comment]
Yes, we want loose coupling of components where possible.  I agree on both
points, some sort of pluggable model is needed and difficult to reach given
where we are.  Also very much agree that planning and design discussions
need to happen so we can figure out what this should look like.  The key
goal would be a minimal attainable model that we could expand on as we have
more time and need more features.

For connecting pluggable components to the Narrative, I would recommend we
talk to @fperez and Jupyter team, since it is quite likely that they are at
least aware of the issues involved.

**Comment by briehl** [comment]
Agreed, Matt. I'd like to get our pluggable components to either be something that Jupyter can directly consume (so we don't have to do any work), or easily wrappable by some Jupyter extension (so we don't have to do too much work).

Either way, on the Narrative end, I think an overall revision of our UI stack will be required to service both the plugins and the interface between them and Jupyter.

There's also the ongoing issue of how to turn our KBase-ified markdown cells into code cells, but I think the first revision will go a long way toward solving that. Still, something to keep in mind.

**Comment by briehl** [comment]
Okay, checking this in now so we can do the CI deployment.

This is also going to mean doing the usual branching in this repo - develop, staging, and then master. So, @hsyoo , please make future PRs against develop. Thanks!

**Pull request merged**
