### PR TITLE
bumping landing pages plugin version

### PR DESCRIPTION
**Pull request by mlhenderson**
0.1.0 -> 0.1.1
https://github.com/kbase/kbase-ui-plugin-data-landing-pages/releases/tag/0.1.1

### CODE REVIEW

**Comment by mlhenderson** [comment]
@eapearson I'm not understanding what version change here had to do with the test failure?

**Comment by eapearson** [comment]
Hey Matt -- the build is failing there is a syntax error in the bower.json of the plugin. Just an trailing comma in dependencies.

**Comment by mlhenderson** [comment]
@eapearson since the build failed because of external code, even though the external code was updated, tests for this PR don't run again without a commit here.  I can try to put in some trivial thing like a comment to trigger a new test run.

**Comment by eapearson** [comment]
The build depends on the tag, so simply a new tag (0.1.2) which carries the fix will cure this ill. By the time you get this I may a PR which updates to 1.0.0 dependencies, and that would be good time for a fresh tag too -- the first step towards getting all the deps into kbase (which will probably not be before tomorrow, since I can't create the repos.)

**Comment by briehl** [comment]
@mlhenderson You can also manually trigger a new test run by going to the Travis build page for this PR and hitting the "Restart build" button in the top right.

**Comment by eapearson** [comment]
Hey Matt, would you mind doing a fresh PR with the changes I just submitted? That will get it synced up with the 1.0.0 mass update for dependencies.

**Comment by mlhenderson** [comment]
Sure, I can resubmit.

**Pull request closed without merging**
