### PR TITLE
New interstitial loading page

### PR DESCRIPTION
**Pull request by briehl**
Cleaned up (a little - there wasn't much to do!) @eapearson 's changes to the Narrative app loading page.

It needed a little cleanup for various dependencies (domReady, the new build info, etc.). I also tweaked the logic when peeking at the Narrative to see if it's loaded. Now, when there's a request timeout, it just loops and tries again, up to the max number of tries. This behavior has certainly been seen before, at least a little bit of lag on page loading.

Other than that, when this page notices that the narrative config file can be found, it just forwards to that container. If it can't find the config file, then things are Very Bad and the page shows an error.

Note that this requires a similar change to the Narrative repo to work.

### CODE REVIEW

**Comment by eapearson** [comment]
I'll go ahead and get this up on CI since it needs to be in place before the Narrative changes.

**Comment by briehl** [comment]
Oh, I see. Yes, I agree on a common linter / set of linting rules. I just saw the .vscode directory and figured it crept in on some commit.

Let's put it in the root of each repo that needs it. That seems to be the standard location from other repos I've browsed.

**Comment by briehl** [comment]
But for now, I agree, let's go ahead and get this up on CI.

**Comment by eapearson** [comment]
You beat me to it, I was just running a quick build test. I'll redeploy kbase-ui CI.
BTW is this fix only going up on auth2? Shouldn't we get it on staging also?

**Comment by briehl** [comment]
Yeah, we should probably get those changes up to staging as well, especially if we're deploying that today. I'll work on the Narrative side.

**Comment by eapearson** [comment]
After we test it on CI, I'll do another Develop->Staging.

**Pull request merged**
