### PR TITLE
Develop->staging [WIP]

### PR DESCRIPTION
**Pull request by kkellerlbl**
Please do not merge yet!  (There are conflicts anyway, I will take a look.)

PR to merge changes for catalog support in -next and -appdev.  They are not strictly required so we can postpone if needed.

### CODE REVIEW

**Comment by kkellerlbl** [comment]
It looks like the conflict is just in travis.yml.

**Comment by kkellerlbl** [comment]
@eapearson I can make a PR to the staging branch to try to fix the travis.yml issue, or you can try to fix it, or you can just merge by hand, whatever you prefer.

Let @msneddon and me know if you think we should put off merging this, so we know what to expect for the weekend and next Tuesday's demos (and the Wednesday appdev deploy).

**Comment by eapearson** [comment]
I'll have a look at that.

I didn't know we were doing this today, I haven't had my eyes on the big picture with kbase-ui for a little while. There are changes in here which probably should not go forward. I mean, next should be fine, but it should not be considered ready for production. 

Remember the data api genome widget issue? It did not provide feature view, so we replaced it with the production one, and put the data api one back into CI. And there are downloaders which had been enabled in dataview for testing, but last I saw were still broken and should not be made available in production

**Comment by kkellerlbl** [comment]
I know, I'm sorry, I just realized that kbase-ui might be helpful.  If I'd been thinking more carefully I would have asked earlier this week.

None of this would move to production, but we would want to move it to production appdev, so it would be production-y for at least SDK developers.  So unless Mike feels very strongly, let's not promote this yet.  I'd rather keep next and prod appdev mostly working and not introduce a regression.

**Comment by kkellerlbl** [comment]
We should still resolve the travis.yml conflict.

**Comment by eapearson** [comment]
yeah, sorry about that, it was the quick change to next out of band with staging ... the same functional change with a few comment line difference. I'll fix that in develop.

**Comment by kkellerlbl** [comment]
Awesome, thanks!

**Comment by msneddon** [comment]
I was thinking some more, and realized that this would be the first UI release with the data<->files pages.  For some reason I had it in my head that the basic page was up already.  So that makes a push to production (or appdev at least) more important.  It still probably doesn't have to go out next week, but it is important to do it soon.  Maybe we can at least try to sort out in the next week what should or should not be included in the next ui update and refactor the repo into branches accordingly.

**Comment by eapearson** [comment]
Sounds good, I think feature branches would be very welcome to help disentangle slower moving efforts from those that are ready to go (and the small incremental improvements we want to keep flowing.)
One issue I guess is how people can share the feature branches, which is what the combo-branch "develop"  and CI are used for. It probably would be feasible, no, to set up automated feature-branch servers if they are narrative + ui running against CI services? Or not so automated semi-permanent servers. Or perhaps individual feature owners should be responsible for setting this up (ala narrative-dev) if they so choose?

**Pull request closed without merging**
