### PR TITLE
UIP-30 update Google Analytics tags

### PR DESCRIPTION
**Pull request by briehl**
# Pull Request

## Description

> * Summarize the changes.
Google's Universal Analytics is going away shortly, to be replaced by Google Analytics 4. This PR swaps out the old tags for the new. No other code changes should be necessary to get analytics flow, so there are no code changes here!

> * List any dependencies involved in this change.
None

## Issues Resolved

> * list Jira tickets resolved in this PR
https://kbase-jira.atlassian.net/browse/UIP-30
https://kbase-jira.atlassian.net/browse/UIP-25

>   e.g.  https://kbase-jira.atlassian.net/browse/PTV-XXX

> * list Github issues resolved by this PR
> 
>   e.g. https://github.com/myrepo/issues/xxx
N/A

* [x] Added the Jira Tickets to the title of the PR e.g. (PTV-XXX fixes a terrible bug)
* [n/a] Added the Github Issue to the title of the PR e.g. (PTV-XXX adds an awesome feature)

## Testing Instructions

> Provide details for testing status and how to test the PR:
  
* [ ] Tests pass locally
* [ ] Tests pass in github actions
* [ ] Manually verified that changes area available (by spinning up an instance and navigating to _X_ to see _Y_)

## Dev Checklist

* [x] Code follows the guidelines at [https://sites.google.com/truss.works/kbasetruss/development](https://sites.google.com/truss.works/kbasetruss/development)
* [x] I have performed a self-review of my own code
* [x] I have commented my code, particularly in hard-to-understand areas
* [x] I have made corresponding changes to the documentation
* [x] My changes generate no new warnings
* [ ] I have added tests that prove my fix is effective or that my feature works
* [x] New and existing unit tests pass locally with my changes
* [ ] Integration tests have been run and fully pass (only when preparing a release)
* [n/a] I have run run the code quality script against the codebase (also done implicitly during a build)

## Release Notes

* [x] Ensure there is an "upcoming release notes" file located in release-notes/RELEASE_NOTES_NEXT.md
* [x] Add relevant notes to this document

## Release

> This section only relevant if this PR is preparing a release

* [ ] Bump version in config/release.yml
* [ ] Rename release-notes/RELEASE_NOTES_NEXT.md to the appropriate release
* [ ] Add release notes document to the release notes index release-notes/index.md

### CODE REVIEW

**Review by eapearson — COMMENTED** [review]
The configs in the repo are just examples.  The real configs are in gitlab. Have those been made too?
In any case, I don't think the GA codes in config are used any more? I'll check. When Akiyo aded the latest round of GA code changes, it hardcoded it into the codebase, which also implied that one GA tag was used for all deployments.
I asked about this, and was told that indeed we didn't care about separating by environment any more.
So do we now have one GA code per environment again? If so, more changes will be necessary to integrate the config into gtag, as was the case before the aforementioned changes.

**Comment by eapearson** [comment]
> The configs in the repo are just examples. The real configs are in gitlab. Have those been made too?

Actually, the configs are not just examples, but also are used in development if gitlab is not accessible. If possible, I usually fetch the gitlab configs once, then use them for that work session, otherwise fall back to the ones in the repo. But they are not used any deployment.

**Comment by briehl** [comment]
> The configs in the repo are just examples. The real configs are in gitlab. Have those been made too?

I wasn't aware of that. I'll ask the admins to make an update.

> Actually, the configs are not just examples, but also are used in development if gitlab is not accessible. 

Ok, so we should keep these here, too. 

> So do we now have one GA code per environment again? If so, more changes will be necessary to integrate the config into gtag, as was the case before the aforementioned changes.

Not really, to my knowledge. I looked through the analytics stack, and really only the production one has been in use. It would probably be nice for the metrics crew to be able to more easily differentiate, so we might consider going back to one config per environment. Or even just splitting them in two - one for prod / appdev, and one for everything else.

**Comment by eapearson** [comment]
> > The configs in the repo are just examples. The real configs are in gitlab. Have those been made too?
> 
> I wasn't aware of that. I'll ask the admins to make an update.
> 
> > Actually, the configs are not just examples, but also are used in development if gitlab is not accessible.
> 
> Ok, so we should keep these here, too.
> 
> > So do we now have one GA code per environment again? If so, more changes will be necessary to integrate the config into gtag, as was the case before the aforementioned changes.
> 
> Not really, to my knowledge. I looked through the analytics stack, and really only the production one has been in use. It would probably be nice for the metrics crew to be able to more easily differentiate, so we might consider going back to one config per environment. Or even just splitting them in two - one for prod / appdev, and one for everything else.

I mean, didn't someone create GA4 codes for each environment, meaning they want them to be used? Just asking. 

It does seem more accurate to separate out internal development, and interesting as well to separate out appdev activity (mixed external and internal - but that separate would be interesting too). There may be a way to do that with the same GA id, but adding an environment tag, though that might complicate the GA reporting.

Anyway, if we decide to do that, more work would be needed - basically to fold the GA stuff back into the codebase so it can be populated by config. But that can be done later, if necessary.

Anyway, looks good otherwise. I'll merge it in and get it deployed to CI so Zach can verify it is working.

(And I realize now that the username had already been added before.)

**Comment by briehl** [comment]
Yeah, I put in GA4 codes, since there were already UA codes for each environment, and I saw the configs for each here. I didn't realize they weren't actually being used.

I think we can effectively do whatever we want with GA tags - put them all on the same property, account, etc. 

But I think those are better questions for the metrics team, and possibly a project that would come out of that later.

Thanks for merging and getting up on CI!

**Comment by eapearson** [comment]
Actually @briehl, I jumped the gun on my SOP. First deploy the PR into CI and let interested parties verify the changes. Then I'll merge it.

**Pull request merged**
