### PR TITLE
Refactor oriented at simplification

### PR DESCRIPTION
**Pull request by eapearson**
Cleaned up some internals which complicated the configuration, specifically some services which were installed as plugins, which introduced inter-plugin dependencies. Yuck.
Quite a bit of cleanup relating to the Bluebird promises lib update -- it issues usage warning messages into the browser console which makes debugging difficult. Many times the warnings help to find suspect nested promises -- addressing all of the messages did improve and simplify code.
Re-introduced development conveniences, specifically external (local development) plugin directory.
Revamped the build process and created a specific dist directory.
Significant (but not fully complete) move towards directory based module namespacing -- module references are by path, and the target javascript file must live on that path in the build or dist product. This simplifies AMD configuration, improves debuggability, and helps isolate module dependencies.

### CODE REVIEW

**Comment by eapearson** [comment]
I'm fixing the travis breakage.

**Comment by briehl** [comment]
Did you mean to check in the whole dist directory? That should probably just be built on compilation.

**Comment by eapearson** [comment]
That was kind of to raise the idea of a release being an actual instance of a final (dist) build. It removes the uncertainty inherent in an unbuilt release -- the final product, due to changes in dependencies or the host environment, may result in a build which is different from the one that was intended for release. Of course, some changes in the host environment may be desirable, so we should move the deploy target handling from the build to the deploy phase...

On the ride home I was just considering the dependency issue too. If we use static dependencies within kbase-ui (no loosey-goosey version expressions; yet hoping that the dependencies themselves are rather loose with their own dependency requirements), then we can have more assurance that the build will be repeatable. As it is, building from scratch may yield a significantly different codebase than was tested in the initial commit of the release.

**Comment by briehl** [comment]
To support the different environments, I think it'll be best to either build it in each env for deployment (or, at the least, keep the config registration script handy so it can inherit from the deploy tools' deploy.cfg).

Using static dependency versioning is a good idea, too, at least in the kbase-ui repo. The subrepos like kbase-ui-plugin-dataview, etc., can probably all manage their own dependencies as needed (though they should use static versions, too).

Another idea, at least for the repos we manage, is to use git tags or versioning as well, if not moving to using the Bower registry and managing version releases through there. Actually, registering with Bower probably the right way to go, since I think the only options for using a direct Github string in a bower file are either a branch or commit hash. @scanon - any thoughts on registering our UI code with a service like Bower? It's not very different (in principle) from CPAN or PyPI.

**Comment by eapearson** [comment]
Exactly, I was just tinkering with the build and deploy phase -- all that really needs doing for deploy is to copy dist to a specified location, and then write a service config file. One tricky bit is development building is that we need to inject the service config earlier, since there is no deployment. The flow to get to deploy is something like this (simplified):
source -> build -> dist -> deploy -> inject config
if the config is injected at deploy, the development build will need to alter the flow so that
source -> build -> inject config
that is no big deal since the newish build process supports that.

Since bower flattens the dependency tree, it is easy to get conflicts if version expressions are too restrictive. It can be overridden, but that is not wonderful. I was thinking though that if kbase-ui at least uses strict versions in dependency configuration, then it will be very stable over a release cycle, right?. Upon a major release we could catch up on what's been happening with dependencies. I was thinking, too, that this would encourage more discipline in following the status of dependencies, and that this could be documented in the commits in which the versions are updated if not in release notes.

Re Bower I'm pretty sure we can use release tags directly, but in any case the bower registry is nicer because we can use shorter, canonical names like everyone else, and version expressions. We can test this out with a local registry.

**Pull request closed without merging**
